import {
  ES3DTileset,
  ESVisibilityAnalysis,
  ESBoxClipping,
  ESPoi2D,
  ESAlarm,
  ESPoi3D,
  ESDynamicWater,
  ESGeoWater,
  ESLevelRuntimeModel,
  ESDataMesh,
  ESPipeline,
  ESPit,
  ESApertureEffect,
  ESCameraVisibleRange,
  ESCar,
  ESClippingPlane,
  ESCzml,
  ESExcavate,
  ESGeoDiv,
  ESGeoJson,
  ESGeoLineString,
  ESGeoPolygon,
  ESGeoRectangle,
  ESGeoVector,
  ESGltfModel,
  ESHuman,
  ESImageLabel,
  ESImageryLayer,
  ESLabel,
  ESLocalCircle,
  ESLocalSkyBox,
  ESLocalVector,
  ESLocalVector2D,
  ESObjectWithLocation,
  ESPath,
  ESPipeFence,
  ESPolygonFence,
  ESPolygonFlattenedPlane,
  ESPolygonWithHole,
  ESSceneObject,
  ESTerrainLayer,
  ESTextLabel,
  ESUnrealActor,
  ESVideoFusion,
  ESViewShed,
  ESVisualObject,
  ESWidget,
  ESFireParticleSystem,
  ESBlastParticleSystem
} from 'earthsdk3'
import { ESKml } from 'earthsdk3-cesium'
export const styleList = [
  { type: ESImageryLayer, name: 'yingxiang' },
  { type: ES3DTileset, name: 'wapian' },
  { type: ESTerrainLayer, name: 'dixing' },
  { type: ESPolygonWithHole, name: 'daidongduobianxing' },
  { type: ESExcavate, name: 'wakeng' },
  { type: ESPolygonFlattenedPlane, name: 'yaping' },
  { type: ESClippingPlane, name: 'caijian' },
  { type: ESPipeFence, name: 'guandaoweilan' },
  { type: ESVideoFusion, name: 'shipinronghe' },
  { type: ESUnrealActor, name: 'actor' },
  { type: ESLocalSkyBox, name: 'tiankonghe' },
  { type: ESTextLabel, name: 'wenzi' },
  { type: ESImageLabel, name: 'tubiaodian' },
  { type: ESPath, name: 'lujing' },
  { type: ESCameraVisibleRange, name: 'shexiangtou' },
  { type: ESViewShed, name: 'keshiyu' },
  { type: ESLocalCircle, name: 'yuan' },
  { type: ESGltfModel, name: 'jianzhu' },
  { type: ESPolygonFence, name: 'dianziweilan' },
  { type: ESHuman, name: 'renyuan' },
  { type: ESAlarm, name: 'baojing' },
  { type: ESGeoJson, name: 'GeoJson' },
  { type: ESKml, name: 'Kml' },
  { type: ESGeoDiv, name: 'zidingyi3' },
  { type: ESCzml, name: 'Czml' },
  { type: ESWidget, name: 'bujian' },
  { type: ESVisibilityAnalysis, name: 'tongshi' },
  { type: ESBoxClipping, name: 'tipaoqie1' },
  { type: ESPoi2D, name: 'poi2D1' },
  { type: ESPoi3D, name: 'poi3D1' },
  { type: ESPit, name: 'keng' },
  { type: ESPipeline, name: 'guanxian1' },
  { type: ESDynamicWater, name: 'jubushuimian1' },
  { type: ESGeoWater, name: 'dilishuimian1' },
  { type: ESDataMesh, name: 'DataMesh1' },
  { type: ESFireParticleSystem, name: 'liziyanhuo1' },
  { type: ESBlastParticleSystem, name: 'lizibaozha1' },
  { type: ESLevelRuntimeModel, name: 'guanqiabao1' },
  { type: ESCar, name: 'cheliang' },
  { type: ESApertureEffect, name: 'guangquantexiao' },
  { type: ESGeoRectangle, name: 'juxing' },
  { type: ESGeoPolygon, name: 'duobianxing' },
  { type: ESGeoLineString, name: 'zhexian' },
  { type: ESGeoVector, name: 'dilishiliang' },
  { type: ESObjectWithLocation, name: 'weizhiduixiang' },
  { type: ESLabel, name: 'biaoqian' },
  { type: ESLocalVector, name: 'jubuzuobiao' },
  { type: ESLocalVector2D, name: 'jubu2Dzuobiao' },
  { type: ESVisualObject, name: 'dituchangjing' }
]
