export const EARTH_UI_SCENEOBJECT_TYPE_ICON: Record<string, string> = {
  Default: "wenjian_weixuanzhong",
  Folder: "wenjian_weixuanzhong",
  ESImageryLayer: "yingxiang",
  ES3DTileset: "wapian",
  ESTerrainLayer: "dixing",
  ESPolygonWithHole: "daidongduobianxing",
  ESExcavate: "wakeng",
  ESPolygonFlattenedPlane: "yaping",
  ESClippingPlane: "caijian",
  ESPipeFence: "guandaoweilan",
  ESVideoFusion: "shipinronghe",
  ESUnrealActor: "actor",
  ESLocalSkyBox: "tiankonghe",
  ESTextLabel: "wenzi",
  ESImageLabel: "tubiaodian",
  ESPath: "lujing",
  ESCameraVisibleRange: "shexiangtou",
  ESViewShed: "keshiyu",
  ESLocalCircle: "yuan",
  ESGltfModel: "jianzhu",
  ESPolygonFence: "dianziweilan",
  ESHuman: "renyuan",
  ESAlarm: "baojing",
  ESGeoJson: "GeoJson",
  ESKml: "Kml",
  ESGeoDiv: "zidingyi3",
  ESCzml: "Czml",
  ESWidget: "bujian",
  ESVisibilityAnalysis: "tongshi",
  ESBoxClipping: "tipaoqie1",
  ESPoi2D: "poi2D1",
  ESPoi3D: "poi3D1",
  ESPit: "keng",
  ESPipeline: "guanxian1",
  ESDynamicWater: "jubushuimian1",
  ESGeoWater: "dilishuimian1",
  ESDataMesh: "DataMesh1",
  ESFireParticleSystem: "liziyanhuo1",
  ESBlastParticleSystem: "lizibaozha1",
  ESLevelRuntimeModel: "guanqiabao1",
  ESCar: "cheliang",
  ESApertureEffect: "guangquantexiao",
  ESGeoRectangle: "juxing",
  ESGeoPolygon: "duobianxing",
  ESGeoLineString: "zhexian",
  ESGeoVector: "dilishiliang",
  ESObjectWithLocation: "weizhiduixiang",
  ESLabel: "biaoqian",
  ESLocalVector: "jubuzuobiao",
  ESLocalVector2D: "jubu2Dzuobiao",
  ESVisualObject: "dituchangjing",
};

export const getIcon = (type: string) =>
  EARTH_UI_SCENEOBJECT_TYPE_ICON[type] ||
  EARTH_UI_SCENEOBJECT_TYPE_ICON.Default;
